/**
 * Generated by Scrooge
 *   version: 3.18.1
 *   rev: 59eb954f8f1bf091a6ddd6e6fb21219aff8cbcc5
 *   built at: 20150430-150955
 */
package com.feynmanliang.searchbird.thrift

import com.twitter.finagle.{SourcedException, Service => FinagleService}
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.finagle.thrift.{Protocols, ThriftClientRequest}
import com.twitter.scrooge.{ThriftStruct, ThriftStructCodec}
import com.twitter.util.{Future, Return, Throw, Throwables}
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.{TMemoryBuffer, TMemoryInputTransport}
import scala.collection.{Map, Set}

import scala.language.higherKinds

/**
 * A simple memcache-like service, which stores strings by key/value.
 * You should replace this with your actual service.
 */
@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class SearchbirdService$FinagleClient(
  val service: FinagleService[ThriftClientRequest, Array[Byte]],
  val protocolFactory: TProtocolFactory = Protocols.binaryFactory(),
  val serviceName: String = "SearchbirdService",
  stats: StatsReceiver = NullStatsReceiver
) extends SearchbirdService[Future] {
  import SearchbirdService._

  protected def encodeRequest(name: String, args: ThriftStruct) = {
    val buf = new TMemoryBuffer(512)
    val oprot = protocolFactory.getProtocol(buf)

    oprot.writeMessageBegin(new TMessage(name, TMessageType.CALL, 0))
    args.write(oprot)
    oprot.writeMessageEnd()

    val bytes = Arrays.copyOfRange(buf.getArray, 0, buf.length)
    new ThriftClientRequest(bytes, false)
  }

  protected def decodeResponse[T <: ThriftStruct](resBytes: Array[Byte], codec: ThriftStructCodec[T]) = {
    val iprot = protocolFactory.getProtocol(new TMemoryInputTransport(resBytes))
    val msg = iprot.readMessageBegin()
    try {
      if (msg.`type` == TMessageType.EXCEPTION) {
        val exception = TApplicationException.read(iprot) match {
          case sourced: SourcedException =>
            if (serviceName != "") sourced.serviceName = serviceName
            sourced
          case e => e
        }
        throw exception
      } else {
        codec.decode(iprot)
      }
    } finally {
      iprot.readMessageEnd()
    }
  }

  protected def missingResult(name: String) = {
    new TApplicationException(
      TApplicationException.MISSING_RESULT,
      name + " failed: unknown result"
    )
  }

  protected def setServiceName(ex: Throwable): Throwable =
    if (this.serviceName == "") ex
    else {
      ex match {
        case se: SourcedException =>
          se.serviceName = this.serviceName
          se
        case _ => ex
      }
    }

  // ----- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_get {
    val RequestsCounter = scopedStats.scope("get").counter("requests")
    val SuccessCounter = scopedStats.scope("get").counter("success")
    val FailuresCounter = scopedStats.scope("get").counter("failures")
    val FailuresScope = scopedStats.scope("get").scope("failures")
  }
  
  def get(key: String): Future[String] = {
    __stats_get.RequestsCounter.incr()
    this.service(encodeRequest("get", get$args(key))) flatMap { response =>
      val result = decodeResponse(response, get$result)
      val exception: Future[Nothing] =
        if (false)
          null // can never happen, but needed to open a block
        else if (result.ex.isDefined)
          Future.exception(setServiceName(result.ex.get))
        else
          null
  
      if (result.success.isDefined)
        Future.value(result.success.get)
      else if (exception != null)
        exception
      else
        Future.exception(missingResult("get"))
    } respond {
      case Return(_) =>
        __stats_get.SuccessCounter.incr()
      case Throw(ex) =>
        setServiceName(ex)
        __stats_get.FailuresCounter.incr()
        __stats_get.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
    }
  }
  private[this] object __stats_put {
    val RequestsCounter = scopedStats.scope("put").counter("requests")
    val SuccessCounter = scopedStats.scope("put").counter("success")
    val FailuresCounter = scopedStats.scope("put").counter("failures")
    val FailuresScope = scopedStats.scope("put").scope("failures")
  }
  
  def put(key: String, value: String): Future[Unit] = {
    __stats_put.RequestsCounter.incr()
    this.service(encodeRequest("put", put$args(key, value))) flatMap { response =>
      val result = decodeResponse(response, put$result)
      val exception: Future[Nothing] =
        null
  
      if (exception != null) exception else Future.Done
    } respond {
      case Return(_) =>
        __stats_put.SuccessCounter.incr()
      case Throw(ex) =>
        setServiceName(ex)
        __stats_put.FailuresCounter.incr()
        __stats_put.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
    }
  }
  private[this] object __stats_search {
    val RequestsCounter = scopedStats.scope("search").counter("requests")
    val SuccessCounter = scopedStats.scope("search").counter("success")
    val FailuresCounter = scopedStats.scope("search").counter("failures")
    val FailuresScope = scopedStats.scope("search").scope("failures")
  }
  
  def search(query: String): Future[Seq[String]] = {
    __stats_search.RequestsCounter.incr()
    this.service(encodeRequest("search", search$args(query))) flatMap { response =>
      val result = decodeResponse(response, search$result)
      val exception: Future[Nothing] =
        null
  
      if (result.success.isDefined)
        Future.value(result.success.get)
      else if (exception != null)
        exception
      else
        Future.exception(missingResult("search"))
    } respond {
      case Return(_) =>
        __stats_search.SuccessCounter.incr()
      case Throw(ex) =>
        setServiceName(ex)
        __stats_search.FailuresCounter.incr()
        __stats_search.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
    }
  }
}