/**
 * Generated by Scrooge
 *   version: 3.18.1
 *   rev: 59eb954f8f1bf091a6ddd6e6fb21219aff8cbcc5
 *   built at: 20150430-150955
 */
package com.feynmanliang.searchbird.thrift

import com.twitter.scrooge.{
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}

/**
 * It's considered good form to declare an exception type for your service.
 * Thrift will serialize and transmit them transparently.
 */
object SearchbirdException extends ThriftStructCodec3[SearchbirdException] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("SearchbirdException")
  val DescriptionField = new TField("description", TType.STRING, 1)
  val DescriptionFieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      DescriptionField,
      false,
      false,
      DescriptionFieldManifest,
      None,
      None,
      immutable$Map(
      ),
      immutable$Map(
      )
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map[String, String](
    )

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: SearchbirdException): Unit = {
  }

  def withoutPassthroughFields(original: SearchbirdException): SearchbirdException =
    new SearchbirdException(
      description =
        {
          val field = original.description
          field
        }
    )

  override def encode(_item: SearchbirdException, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  override def decode(_iprot: TProtocol): SearchbirdException = {
    var description: String = null
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                description = readDescriptionValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'description' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new SearchbirdException(
      description,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    description: String
  ): SearchbirdException =
    new SearchbirdException(
      description
    )

  def unapply(_item: SearchbirdException): Option[String] = Some(_item.description)


  private def readDescriptionValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  private def writeDescriptionField(description_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DescriptionField)
    writeDescriptionValue(description_item, _oprot)
    _oprot.writeFieldEnd()
  }

  private def writeDescriptionValue(description_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(description_item)
  }


}

class SearchbirdException(
    val description: String,
    val _passthroughFields: immutable$Map[Short, TFieldBlob])
  extends ThriftException with com.twitter.finagle.SourcedException with ThriftStruct
  with scala.Product1[String]
  with java.io.Serializable
{
  import SearchbirdException._
    def this(
      description: String
    ) = this(
      description,
      Map.empty
    )

  def _1 = description

  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: Some[TFieldBlob] => blob
      case None => {
        val _fieldOpt: Option[TField] =
          _fieldId match {
            case 1 =>
              if (description ne null) {
                writeDescriptionValue(description, _oprot)
                Some(SearchbirdException.DescriptionField)
              } else {
                None
              }
            case _ => None
          }
        _fieldOpt match {
          case Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            Some(TFieldBlob(_field, _data))
          case None =>
            None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): SearchbirdException = {
    var description: String = this.description
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        description = readDescriptionValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new SearchbirdException(
      description,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): SearchbirdException = {
    var description: String = this.description

    _fieldId match {
      case 1 =>
        description = null
      case _ =>
    }
    new SearchbirdException(
      description,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetDescription: SearchbirdException = unsetField(1)


  override def write(_oprot: TProtocol): Unit = {
    SearchbirdException.validate(this)
    _oprot.writeStructBegin(Struct)
    if (description ne null) writeDescriptionField(description, _oprot)
    _passthroughFields.values.foreach { _.write(_oprot) }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    description: String = this.description,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): SearchbirdException =
    new SearchbirdException(
      description,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[SearchbirdException]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[SearchbirdException]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)

  override def getMessage: String = String.valueOf(description)

  override def productArity: Int = 1

  override def productElement(n: Int): Any = n match {
    case 0 => this.description
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "SearchbirdException"
}